### PR TITLE
Complete spell list (879) converted to Ritual Magic Spells.

### PR DESCRIPTION
**Pull request by jbhuddleston**

### CODE REVIEW

**Comment by jbhuddleston** [comment]
First attempt at a PR. Please let me know if I need to do something else next time.

**Comment by richardwilkes** [comment]
These don't look like they load correctly. I suspect the logic that saves & loads Ritual Magic in GCS wasn't tested very well and that there is an issue there. I'll need to do some work (and a new bug-fix release) before these can be considered (which may in turn require some changes to this file).

**Comment by jbhuddleston** [comment]
My apologies. When the list opened and each RMS opened correctly in the editor from the list I 'assumed' they were good to go.
I copied one to a character and it opened as a regular spell. I then created one from scratch in the character and it worked correctly.
Finally, I compared the two versions of the spell in the character sheet code and found that the one copied from the RMS list is missing the base_skill and prereq_count fields. The wrapper is also <spell version="5"> instead of <ritual_magic_spell version="1">. Those are the only differences I spotted.
Regards

**Comment by jbhuddleston** [comment]
Hmm. The editor removed a portion of my statement "the wrapper is also <spell version="5"> instead..."

**Comment by jbhuddleston** [comment]
One more try. spell version="5"

**Comment by richardwilkes** [comment]
Yeah, I don't think this is due to anything you did/didn't do. I believe the code was not updated to correctly write the changes to disk, so my fault for not catching that earlier, at least in the review I did of the submitted work.

**Comment by jbhuddleston** [comment]
I believe the issue occurs only when copying the RMS from its' list to the character sheet.

I have saved and reloaded the character sheet with no change to the file.
I edited the improperly copied spell to correct the errors and omissions and it loaded and saved correctly from then on.
I can open an RMS in the list and the RMS Editor displays it correctly.
But, copy it to a character and it arrives as a regular spell.

**Comment by richardwilkes** [comment]
Found and fixed the issue preventing moving the ritual magic spell to a character sheet or template... however, further testing seems to show that the level is not being calculated. It stays at the Ritual Magic (xxx) skill level no matter what you spend on it. I assume that's wrong. I've never used Ritual Magic Spells nor have I even read much about them, as I didn't need them. I had assumed that the contributed code was doing the right thing here as well... yet I'm pretty sure it isn't. Anyway, I need to dig into this further... although I'm beginning to wonder if I should bother, as this has been in a couple of releases now and clearly no one has even tried it. :-(

**Comment by jbhuddleston** [comment]
I had a look at the code but am pretty rusty and couldn't find the source of the problem, only the symptoms.
Heh, I didn't expect the point value problem; it looked pretty straightforward. I don't like the relative lack of difference between Average and Hard techniques anyway, and was going to ask if you could implement an alternate option. I thought it would be too difficult to bother you with and I don't know how much you like to stray from canon anyway. I feel that Hard techniques should cost twice Average ones because +1 point is almost the same as increasing the default penalty by 1.
Anyhow, I think it is possible that no-one has tried to use them because they have to build a whole magic system around them and that is a lot of work. I was building a magic system from scratch anyway and so took it on. My Middle Earth Dwarven Enchanters will appreciate the work you have put into this :-) and I will help you any way I can.

**Comment by jbhuddleston** [comment]
I just tried out the RMS I created on a character sheet and the point value works. The skill defaults at -15 so it takes a few to even reach 0; 16 pts to reach the base skill. Tried a second one with the same result.

**Comment by richardwilkes** [comment]
Hmm... I tried it out on a 3-spell chain... Ignite Fire, Extinguish Fire and Slow Fire (each needs the previous). The first thing that leaped out at me was that Ignite Fire showed as valid (did not turn red) despite not having any points in it. That seems wrong... but could be part of the rules -- like I said, I'm not familiar with them. I then added a point to Ignite Fire, which turned Extinguish Fire valid (but still left Slow Fire invalid). I then added a point to Extinguish Fire, turning Slow Fire valid. So, Slow Fire had 0 points and the other two had 1. The Ritual Magic (Fire) skill that I added only had a single point in it, so its skill was 7... and so were all 3 spells. Adding points to any/all of them made no difference in their levels. Any adjustments to the Ritual Magic (Fire) skill adjusted the spells in identical fashion. Needless to say, that seems completely broken to me.

**Comment by richardwilkes** [comment]
Ah... I see the issue now... they all have a prerequisite count of 0, which I'm sure is not right.

**Comment by richardwilkes** [comment]
Yet in the spell list, their prerequisite counts are set to seemingly reasonable values... so my fix for the transfer isn't quite 100% yet. Will work on that some more.

**Comment by jbhuddleston** [comment]
There are a number of choices for RMS behaviour in the rules. They are really guidelines in effect as there are so many options. They all require that the spells behave as techniques. I believe the simplest choice is to have a core IQ/VH skill (Ritual Magic or Thaumatology for example) and all of the colleges are IQ/VH skills which default to it. Each spell is a H technique which defaults to the college that produces the best result. Because the prereq_count may vary depending on the college chosen, the best choice may not be the one with the highest skill. (yep, way complicated...). Otherwise the actual prerequisites are supposed to be ignored (except for non-magical ones if you wish; this is why I left them all in as it is easier to remove them than add them) and that is giving you some false readings.

**Comment by jbhuddleston** [comment]
I believe it makes more sense for the colleges to be techniques as well but they aren't hard enough, hence my poorly veiled request earlier. :-) The difference between H and VH skills disappears without an appropriate separation method, although there are some insanely high prereq counts (at least one is 32)
When you implement this fix, players will have the tools to build their own system or follow any number of the recommended choices. Up until this point they could not. Thanks much for whacking this particular mole.

**Comment by richardwilkes** [comment]
OK, I think I have all the blatant bugs fixed now. I'll make a release with them shortly.

**Comment by richardwilkes** [comment]
Once I've pushed the release, I'll merge this PR. Thanks!

**Review by richardwilkes — APPROVED** [review]

**Pull request merged**
