### PR TITLE
Updated NPC output template to new hierarchical keys

### PR DESCRIPTION
**Pull request by crnormand**
Sorry, I forgot to change the output file for NPCs as well.   Oddly, Fantasy Grounds has two different formats for character imports (and I hadn't gotten around to re-testing NPCs).

Yes, I see the multiple commits again.   After you merge this change, I will delete and then re-clone (hopefully that will resolve the issue

### CODE REVIEW

**Comment by crnormand** [comment]
Oh, and removed the unnecessary bow from the Basic Set equipment.  I assumed sometime after you created that inventory, you built the ability to build damage based on "sw" and "thr".  So there is no need for the strength specific bows anymore

**Comment by richardwilkes** [comment]
Regarding your last commit, "Removed unnecessary Bows based on strength"... my understanding based on B270's statement of "Bows, crossbows, and prods have their own ST value" requires these entries, as they cannot be based off of the user's ST score.

**Comment by crnormand** [comment]
Oh.  shoot (no pun intended).   How do I revert the last commit then?

**Comment by crnormand** [comment]
I have more changes to the library files.... is it ok if I keep pushing, or should I wait for this pull request to be accepted, and then make a new one?

**Pull request closed without merging**
